import os

from decouple import config

DATABASE_HOST = config("DATABASE_HOST")
DATABASE = config('DATABASE_NAME')
DATABASE_USER = config('DATABASE_USER')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')

STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")

HUBSPOT_API_KEY = config("HUBSPOT_API_KEY")

SENDGRID_API_KEY = config('SENDGRID_API_KEY')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
WELCOME_MESSAGE_TEMPLATE_ID = config('WELCOME_MESSAGE_TEMPLATE_ID')
PAYMENT_CONFIRMATION_TEMPLATE_ID = config('WELCOME_MESSAGE_TEMPLATE_ID')
