from decouple import config

DATABASE_HOST = config("DATABASE_HOST")
DATABASE = config('DATABASE_NAME')
DATABASE_USER = config('DATABASE_USER')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')

STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")

HUBSPOT_API_KEY = config("HUBSPOT_API_KEY")
