"""rename created and modified field for charge model

Revision ID: 479a101db0bb
Revises: a9e00646e1d7
Create Date: 2022-05-27 12:12:42.945570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '479a101db0bb'
down_revision = 'a9e00646e1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('charge', sa.Column('modified', sa.DateTime(), nullable=True))
    op.drop_column('charge', 'created_at')
    op.drop_column('charge', 'modified_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('charge', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('charge', 'modified')
    op.drop_column('charge', 'created')
    # ### end Alembic commands ###
