"""add created_at and modified_at to charge table

Revision ID: 573a2f55e475
Revises: 3f4f812d4ca6
Create Date: 2022-05-26 19:50:38.717366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573a2f55e475'
down_revision = '3f4f812d4ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('charge', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge', 'modified_at')
    op.drop_column('charge', 'created_at')
    # ### end Alembic commands ###
