"""remove unique constraint

Revision ID: 5bf098d393cd
Revises: 9b9c2855cad1
Create Date: 2022-05-26 20:04:41.897338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf098d393cd'
down_revision = '9b9c2855cad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
