"""add active field to contact table

Revision ID: 6d11f960f1a5
Revises: 64c38ea8a78f
Create Date: 2022-05-17 11:51:50.109560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d11f960f1a5'
down_revision = '64c38ea8a78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'active')
    # ### end Alembic commands ###
