"""alter organization model

Revision ID: 71886cd76b25
Revises: d15215db454c
Create Date: 2022-05-19 12:44:56.918818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71886cd76b25'
down_revision = 'd15215db454c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'organization', ['name'])
    op.create_unique_constraint(None, 'organization', ['org_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_constraint(None, 'organization', type_='unique')
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
