"""alter charge_id nullable to false

Revision ID: 72ca14fa8b9e
Revises: e0da39a6bed1
Create Date: 2022-05-17 11:21:49.740043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ca14fa8b9e'
down_revision = 'e0da39a6bed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payment', 'charge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payment', 'charge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
