"""add organization foreign key to contact

Revision ID: 873f4fb17cc8
Revises: 6d11f960f1a5
Create Date: 2022-05-17 11:57:19.389214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873f4fb17cc8'
down_revision = '6d11f960f1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'contact', ['email'])
    op.create_foreign_key(None, 'contact', 'organization', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_column('contact', 'org_id')
    # ### end Alembic commands ###
