"""add_message_table

Revision ID: 913be17e323f
Revises: 71886cd76b25
Create Date: 2022-05-21 11:42:37.026628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913be17e323f'
down_revision = '71886cd76b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('message_type', sa.Enum('EMAIL', 'SMS', name='messagetype'), nullable=False),
    sa.Column('carrier', sa.Enum('SENDGRID', 'TWILIO', name='carrier'), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_message_id'), 'message', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
