"""add unique constraint for charge type and org_id for charge table

Revision ID: 9b9c2855cad1
Revises: 573a2f55e475
Create Date: 2022-05-26 19:53:14.981004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9c2855cad1'
down_revision = '573a2f55e475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
