"""modify relationship

Revision ID: a980495e9ab1
Revises: 873f4fb17cc8
Create Date: 2022-05-19 10:31:01.704712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a980495e9ab1'
down_revision = '873f4fb17cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
