"""modify unique constraint

Revision ID: a9e00646e1d7
Revises: ad9ebc89187d
Create Date: 2022-05-26 23:23:53.573992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e00646e1d7'
down_revision = 'ad9ebc89187d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'charge', ['org_id', 'charge_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge', type_='unique')
    # ### end Alembic commands ###
