"""add unique constraint to charge

Revision ID: ad9ebc89187d
Revises: 5bf098d393cd
Create Date: 2022-05-26 20:05:35.891406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9ebc89187d'
down_revision = '5bf098d393cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
