"""modify organization backref

Revision ID: d15215db454c
Revises: a980495e9ab1
Create Date: 2022-05-19 11:57:34.656839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15215db454c'
down_revision = 'a980495e9ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
