"""create payment table

Revision ID: e0da39a6bed1
Revises: f5bac25e3c22
Create Date: 2022-05-17 11:20:29.475825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0da39a6bed1'
down_revision = 'f5bac25e3c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Payment_id'), 'Payment', ['id'], unique=False)
    op.create_index(op.f('ix_Payment_transaction_id'), 'Payment', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Payment_transaction_id'), table_name='Payment')
    op.drop_index(op.f('ix_Payment_id'), table_name='Payment')
    op.drop_table('Payment')
    # ### end Alembic commands ###
