"""create charge table

Revision ID: f5bac25e3c22
Revises: 60809261b623
Create Date: 2022-05-17 11:20:01.803699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bac25e3c22'
down_revision = '60809261b623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'GBP', 'KES', 'INR', name='currency'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.Enum('ONBOARDING', 'MAINTENANCE', name='chargetype'), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_id'), 'charge', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charge_id'), table_name='charge')
    op.drop_table('charge')
    # ### end Alembic commands ###
